### PR TITLE
Describe how to remove a registered package

### PR DESCRIPTION
**Pull request by mzaffalon**
The wording has shamelessly been stolen from https://discourse.julialang.org/t/deregister-package-from-local-registry/76992.

### CODE REVIEW

**Comment by GunnarFarneback** [comment]
This is ok to document but it shouldn't be something done frequently so I'd rather have it on a subpage linked from `Advanced Topics`.

**Comment by mzaffalon** [comment]
What about leaving where it is and saying that this is not done frequently? The text is short and `Advanced Topics` have each a separate page.

**Comment by goerz** [comment]
On a *local* registry, maybe deleting a package is not quite so uncommon: I use a local registry for any package I'm developing that's not yet in General, but then later on when it's registered in General, I'll delete it from the local registry.

**Comment by GunnarFarneback** [comment]
Yes, there are valid reasons to remove packages and you may of course do whatever you want with your own registry, but I won't document it on the front page.

**Comment by mzaffalon** [comment]
I pushed a new change as you requested.

**Comment by GunnarFarneback** [comment]
Thanks.

**Comment by mzaffalon** [comment]
And thank you for the useful package.

**Pull request merged**
