### PR TITLE
Clarify that repository URL may also be path, and must be a bare repo

### PR DESCRIPTION
**Pull request by jakobnissen**
Add a few lines to README and `create_registry` docstring.

### CODE REVIEW

**Comment by GunnarFarneback** [comment]
I'm a bit torn on this. Whether the repo is at a local path seems somewhat secondary since the need for a bare repository is the same regardless, although it's less likely that you have anything else if you create a repo on a git hosting service.

**Comment by jakobnissen** [comment]
I can re-phrase it to be clearer that it must always be bare, but to be careful about this when specifying a local repo as repository "URL"?

**Comment by jakobnissen** [comment]
Rephrased now.

**Comment by GunnarFarneback** [comment]
Thanks for the contribution.

**Pull request merged**
