### PR TITLE
Better error messages for non-package projects

### LINKED ISSUE #60: Requesting better error message for non-packages
I just accidentally attempted to put a DrWatson project into my registry and spent a while figuring out why it wouldn't work. The stated error is that `check_version!` doesn't work on `nothing` (see below). That makes sense because a project isn't a package, and so doesn't have a version number. It doesn't make sense to put a non-package into a registry so this *should* fail, but I would prefer a better error message so that no one wastes the half hour I just wasted.

My suggestion is that when the UUID is loaded, if it's `nothing` immediately error with the message `Project.toml has no UUID. Is $(package_name) a package?` This makes sense to me because all packages need UUIDs.

I'm happy to make the PR this weekend.

```
julia> register("./NeonateTriCorr", registry = "SmithThesisRegistry")
┌ Info: Registering package
│   package_path = "/home/graham/git/NeonateTriCorr"
│   registry_path = "/home/graham/.julia/registries/SmithThesisRegistry"
│   package_repo = "https://github.com/grahamas/NeonateTriCorr.git"
│   uuid = nothing
│   version = nothing
│   tree_hash = "acebe5e97e155b073082cd8e6939ba74dc50e4c0"
└   subdir = ""
HEAD is now at 1601a1b New package: TriCorrApplications v0.2.0
Removing N/NeonateTriCorr/
Already on 'main'
Your branch is up to date with 'origin/main'.
ERROR: MethodError: no method matching check_version!(::Nothing, ::Vector{VersionNumber}, ::RegistryTools.ReturnStatus)
Closest candidates are:
  check_version!(::VersionNumber, ::Vector{VersionNumber}, ::RegistryTools.ReturnStatus) at ~/.julia/packages/RegistryTools/Epat9/src/register.jl:183
Stacktrace:
 [1] check_versions!(pkg::Pkg.Types.Project, versions_data::Dict{String, Any}, status::RegistryTools.ReturnStatus)
   @ RegistryTools ~/.julia/packages/RegistryTools/Epat9/src/register.jl:371
 [2] check_and_update_registry_files(pkg::Pkg.Types.Project, package_repo::String, tree_hash::SubString{String}, registry_path::String, registry_deps_paths::Vector{String}, status::RegistryTools.ReturnStatus; subdir::String)
   @ RegistryTools ~/.julia/packages/RegistryTools/Epat9/src/register.jl:575
 [3] do_register(package::String, registry::String; commit::Bool, push::Bool, branch::Nothing, repo::Nothing, ignore_reregistration::Bool, gitconfig::Dict{Any, Any}, create_gitlab_mr::Bool)
   @ LocalRegistry ~/.julia/packages/LocalRegistry/I8u9h/src/LocalRegistry.jl:247
 [4] do_register
   @ ~/.julia/packages/LocalRegistry/I8u9h/src/LocalRegistry.jl:156 [inlined]
 [5] #register#2
   @ ~/.julia/packages/LocalRegistry/I8u9h/src/LocalRegistry.jl:149 [inlined]
 [6] top-level scope
   @ REPL[6]:1
```

### PR DESCRIPTION
**Pull request by grahamas**
Closes #60.

Checks that the Project.toml defines both `version` and `uuid`, and tells the user that it is missing if they are not found.

Also adds tests for these cases.

Currently two problems:
1) There's a failing test on my machine (see below). The failure is independent of my tests, though.
2) Properly, should also check that the Project.toml is associated with a file `$(project_dir)/src/$(package_name).jl` that defines a module of the correct name. I have a discourse post up to see if checking for being  a valid package is already a solved problem (https://discourse.julialang.org/t/canonical-way-to-check-if-a-project-is-a-package/90827). 

The error I get during testing (both with and without the changes on this branch)
```
Initialized empty Git repository in /tmp/LocalRegistryTestsGKMtSM/upstream/
error: src refspec master does not match any
error: failed to push some refs to 'file:///tmp/LocalRegistryTestsGKMtSM/upstream'
Register tests: Error During Test at /home/graham/git/LocalRegistry.jl/test/runtests.jl:35
  Got exception outside of a @test
  LoadError: failed process: Process(`git -C /tmp/LocalRegistryTestsGKMtSM/TestRegistryPush -c user.name=LocalRegistryTests -c user.email=localregistrytests@example.com push -u origin master`, ProcessExited(1)) [1]
  
  Stacktrace:
    [1] pipeline_error
      @ ./process.jl:565 [inlined]
    [2] run(::Cmd; wait::Bool)
      @ Base ./process.jl:480
    [3] run
      @ ./process.jl:477 [inlined]
    [4] create_registry(name_or_path::String, repo::String; description::Nothing, gitconfig::Dict{String, String}, uuid::Nothing, push::Bool)
      @ LocalRegistry ~/git/LocalRegistry.jl/src/LocalRegistry.jl:81
    [5] (::var"#48#49")(testdir::String)
      @ Main ~/git/LocalRegistry.jl/test/register.jl:228
    [6] with_testdir(f::var"#48#49")
      @ Main ~/git/LocalRegistry.jl/test/utils.jl:160
    [7] top-level scope
      @ ~/git/LocalRegistry.jl/test/register.jl:222
    [8] include(fname::String)
      @ Base.MainInclude ./client.jl:476
    [9] macro expansion
      @ ~/git/LocalRegistry.jl/test/runtests.jl:36 [inlined]
   [10] macro expansion
      @ ~/.local/opt/julia-1.8.3/share/julia/stdlib/v1.8/Test/src/Test.jl:1360 [inlined]
   [11] top-level scope
      @ ~/git/LocalRegistry.jl/test/runtests.jl:36
   [12] include(fname::String)
      @ Base.MainInclude ./client.jl:476
   [13] top-level scope
      @ none:6
   [14] eval
      @ ./boot.jl:368 [inlined]
   [15] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:276
   [16] _start()
      @ Base ./client.jl:522
  in expression starting at /home/graham/git/LocalRegistry.jl/test/register.jl:222
```

### CODE REVIEW

**Comment by GunnarFarneback** [comment]
1. Looks like a plausible master/main clash. Cf #58.
2. Checking the existence of a `src/$(package_name).jl` file is definitely enough. Any further would be going into linter territory, which is rather out of scope for this package.

**Comment by grahamas** [comment]
Ok, I think it's all done. It now checks for 1) version number, 2) UUID, and 3) module file at src/pkg_filename.jl. With tests for all three checks. It also tests handling package names like Flux.jl and Flux.exe and Flux.exe.jl correctly (I'm not totally sure the .exe is legal but like you said, not trying to be a linter--- local registries could do something weird).

You were right about the test failure: the tests run fine on my machine when I change defaultBranch to master.

aside: is `register` supposed to return nothing? why not return `do_register`?

**Comment by GunnarFarneback** [comment]
> It also tests handling package names like Flux.jl and Flux.exe and Flux.exe.jl correctly

You've been overthinking this. The repository might be named `Flux.jl` but the package can't possibly be. `Flux.jl` would be syntax for the `jl` submodule of the `Flux` module.

**Comment by GunnarFarneback** [comment]
> is register supposed to return nothing?

Yes, that's intentional. Cf https://github.com/GunnarFarneback/LocalRegistry.jl/pull/22#issuecomment-727644620.

**Comment by grahamas** [comment]
Oof you're right. I got rid of the code accounting for that "possibility" in this commit.

**Comment by GunnarFarneback** [comment]
Looks great, thanks

**Pull request merged**
